#join token
token: 

ansible_sudo_pass: "P@ssw0rd"
os_veriosn: xUbuntu_20.04
crio_version: "1.20"
become_method: sudo

additional_san: "kube.in.ua,10.100.10.10"

# deploy kubernetes in cluster config
ha_k8s: "yes"
ha_k8s_ip: "10.100.10.10"
ha_k8s_cidr: "24"
ha_k8s_int: "eth1"
ha_k8s_broadcast: "10.100.10.255"
# Test part for vagrant
ansible_connection: ssh
ansible_user: vagrant
ansible_ssh_pass: vagrant