- name: new certificates for bootstraping
  become: yes
  shell: kubeadm init phase upload-certs --upload-certs --kubeconfig=/etc/kubernetes/admin.conf
  run_once: true
  register: certificate_key
  when:
    - inventory_hostname in groups['k8s_masters']
    - inventory_hostname == play_hosts[0]

- name: Generate join command for masters
  become: yes
  shell: "kubeadm token create --certificate-key {{ certificate_key.stdout_lines[-1] }} --print-join-command --kubeconfig=/etc/kubernetes/admin.conf"
  register: join_masters_command
  run_once: true
  when:
    - inventory_hostname in groups['k8s_masters']
    - inventory_hostname == play_hosts[0]

- debug: msg="{{ join_masters_command }}"

- name: Pause for 5 minutes to first master reboot
  pause:
    minutes: 5

- name: Join masters to clusters
  become: yes
  shell: "{{ join_masters_command.stdout }} --apiserver-advertise-address {{ inventory_hostname }}"
  throttle: 1
  when:
    - inventory_hostname in groups['k8s_masters']
    - inventory_hostname != play_hosts[0]

- name: Generate join command for workers
  become: yes
  shell: kubeadm token create --print-join-command --kubeconfig=/etc/kubernetes/admin.conf
  register: join_worker_command
  run_once: true
  when:
    - inventory_hostname in groups['k8s_masters']
    - inventory_hostname == play_hosts[0]

- name: Join workers to clusters
  become: yes
  shell: "{{ join_worker_command.stdout }}"
  when:
    - inventory_hostname in groups['k8s_workers']
